#!/bin/sh
docker run -d -e POSTGRES_PASSWORD=supersecret --name pagination -p 127.0.0.1:5432:5432 -v "$(pwd)"/scripts:/scripts:ro postgres

sleep 1

docker exec -it pagination psql -U postgres -f /scripts/seed.sql