DROP TABLE IF EXISTS "Blogs";

CREATE TABLE "Blogs" (
    "Id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "Name" TEXT,
    "LastUpdated" DATE DEFAULT(now())
);

DO $$BEGIN
FOR i IN 1..1000000 LOOP
    INSERT INTO "Blogs" ("Name", "LastUpdated") VALUES (i::TEXT, now() + INTERVAL '1 day' * (i / 5));
END LOOP;
END$$;

SELECT * FROM "Blogs" LIMIT 100;