DROP TABLE IF EXISTS "Blogs";

CREATE TABLE "Blogs" (
    "Id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "Name" TEXT,
    "LastUpdated" DATE DEFAULT(now())
);

CREATE INDEX IF NOT EXISTS "IX_Blogs_LastUpdated_Id" ON "Blogs" ("LastUpdated" ASC, "Id" ASC);

DO $$BEGIN
FOR i IN 1..1000000 LOOP
    INSERT INTO "Blogs" ("Name", "LastUpdated") VALUES ('Entry ' || i::TEXT, make_date(2022, 11, 10) + INTERVAL '1 day' * (i / 5));
END LOOP;
END$$;
